parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    CompanyRoulette\:
        resource: '../src/*'
        exclude: '../src/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    CompanyRoulette\UserInterface\Http\Web\Controller\:
        resource: '../src/UserInterface/Http/Web/Controller'
        tags: ['controller.service_arguments']
